helpers/any.js
test/helpers/any.js

While working with templates, it's often helpful to be able to output
content if any one of several arguments is valid. (For instance, only
show a product tab if there is warranty info OR shipping info. Only
show social icons wrapper if any one of the icons is present, etc.)
- Add or helper based off the existing "if" helper - content will
render if any/at least one of the arguments supplied validates
- Add some basic tests to verify the functionality of the or helper

Add "or" helper to output content if/or

---

helpers/all.js
test/helpers/all.js

It's possible with handlebars currently to test against multiple
conditions simply by nesting if loops. However, it becomes difficult
when there are more than just a couple arguments that need to be
nested, and it's not possible to use an else conditional for the event
that one is missing.
- Add an #all helper that can be supplied multiple arguments and will
render the block so long as they're all "truthy"
- Include some test coverage for the all helper.

Add #all helper for testing multiple conditions

---

helpers/replace.js
package.json
test/helpers/replace.js

Handle undefined haystack values.
A case came up where a theme was using the helper with an undefined haystack and this caused a 500 error for the pages involved.

Make replace helper more sturdy

---

helpers/getImage.js
package.json
test/helpers/getImage.js

- Fallback to use a string attribute from the theme_settings
- Validates if is a valid image object
- more validation and tests
@hegrec @bc-ejoe @mickr @sherrybc

getImage helper refactor

---

index.js
test/helpers/cdn.js

This pull request allows theme creators to define custom CDN endpoints, and use them via the `cdn` handlebars helper.
When designing themes for BigCommerce, theme designers might want to include large, high resolution image assets as components of their theme. For example on maruccisports.com, each product category includes a 5120x2536 background image, most of which are between 3 and 5 MB. Since sending that much image data down the wire is a poor user experience, we use Imgix to resize and reformat the images depending on the device viewing them. A theme designer might want to use a local version of the image in development, and a version on a CDN like Imgix in production. This pull request allows the designer to define endpoints in their theme's `config.json` file like this:
```json
{ …
```

Enable support for custom defined CDN endpoints

---

helpers/if.js
test/helpers/if.js

adds the ability to use the if helper as a subexpression
context:
https://github.com/assemble/handlebars-helpers/issues/224
https://github.com/assemble/handlebars-helpers/pull/225/files#diff-63430960261956d4a86cbd6cf21d229aR539
why:
to prevent this kind of thing:  https://github.com/bigcommerce/stencil/blob/28eea2f9e8e88b4fdc43a2bc01c264d2989261f9/templates/components/products/card.html#L84-L98
instead it could be:
```
{{#or customer if(theme_settings.restrict_to_login '===' false)}}
<div class="card-text" data-test-info-type="price">
{{> components/products/price price=price customer=../../customer}}
</div>
{{else}}
<div class="card-text" data-test-info-type="price">
<p translate>Log in for pricing</p>
</div>
{{/or}}
```
or
```
{{#all theme_settings.restrict_to_login if(customer '!=' …
```

adjust if helper to support subexpressions

---

index.js

this method was extracted from stencil-cli:
https://github.com/bigcommerce/stencil-cli/blob/master/server/plugins/renderer/responses/pencil-response.js#L34-L70
it also has an additional line which sets the context template_file field to the templatePath:
https://github.com/bigcommerce/paper/compare/bigcommerce:master...mjschock:MERC-1554?expand=1#diff-168726dbe96b3ce427e7fedce31bb0bcR260

renderTheme method

---

index.js
package.json

Turns out we can not change `template_file` to point to a custom template because it is used as the page type by Cornerstone and all its custom themes. (This is what broke custom templates this morning)
Cornerstone uses `template_file`as a map to load classes:
The proposed solution is to deprecate `template_file` and use `template` instead
@mattolson @lord2800 @bc-julianleong

STENCIL-2919 template_file issue fix

---

lib/localizer.js
package.json

https://jira.bigcommerce.com/browse/BIG-29681
Stapler should not crash if there is a syntax error in translation files
@lord2800 @mjschock

BIG-29681 catch MerssageFormat syntax errors

---

helpers/truncate.js
test/helpers/truncate.js

**FUNCTION**
truncate(str, length)
**DESCRIPTION (WHAT)**
Returns the first X characters in a string (unless it reaches the end 
of the string first, in which case it will return fewer). Returns a 
new string that is truncated to the given length.
**USE CASE (WHY)**
As a merchant, I want to display a card, at the bottom of
my home page that highlights the most recent blog post. In the card,
I want to display the blog thumbnail, title and the first 40 characters
of the post's body. In order to extract the first 40 characters, I need
a Handlebars helper that works like the javascript substring() function. 
**USAGE**
{{lang (truncate 'blog.post.body.' 40) }}
@mcampa , @junedkazi , @mjschock

Added a handlebars helper to truncate a string

---

helpers/truncate.js
package.json
test/helpers/truncate.js

* #106 added a truncation helper. It uses `String.prototype.substring` to truncate strings. However, the native function doesn't handle unicode characters properly. So, if you call the truncate helper on strings containing unicode characters (some non-English characters or emoji), you won't get what you expect.
* To save time, I decided to use a third party library called [stringz](https://www.npmjs.com/package/stringz). It has MIT license, so we should be good to use.
* This is necessary because we need to support multiple languages in Stencil.
* Unit
@bigcommerce/checkout @bigcommerce/stencil-team

Fix the truncation of unicode strings

---

README.md
index.js

* Update docs to describe the interface required by paper
for assembler and callbacks
* Minor bug fix in constructor

Update docs & minor fix

---

helpers/stylesheet.js
index.js
test/helpers/cdn.js
test/helpers/stylesheet.js
test/index.js

- Move the config id on the css to css file name
- Remove the config id from asset file path to make sure the assets continue to server from the cdn & the cache is still maintained & not busted since they don’t change per configuration.

STENCIL-3361 Remove configId from assets urls

---

helpers/thirdParty.js
test/helpers/thirdParty.js

* this adds the `{{thumbnailImage}}` helper and removes the non-existent `{{thumbnail}}` helper.
* you can now use the helper as shown below
* https://github.com/helpers/handlebars-helpers/blob/master/lib/html.js#L203
* https://github.com/helpers/handlebars-helpers/blob/master/test/html.js#L147
@bigcommerce/stencil-team @bookernath

STENCIL-3323 - Fix thumbnailImage helper

---

.eslintrc
.travis.yml
helpers/region.js
index.js
test/helpers/region.js

What:
Add an attribute to Paper to use for rendering store content.
Also - converts Paper to using ES6 style classes.

Region Helper - Paper - MERC-2432

---

helpers/if.js
test/helpers/if.js

Customers are trying to use "unless" with operators, the same way "if" works, but we have not implemented this helper.
@bigcommerce/stencil-team

STENCIL-3845 Unless helper

---

helpers/region.js
test/helpers/region.js

Always render region container even if there are no widgets for that region
@mattolson 
@pedelman

MERC-2894 always render region container

---

CHANGELOG.md
index.js
package.json

* Bump paper-handlebars to 3.0
* We no longer store `siteSettings` and `themeSettings` directly on the paper object.
* Create accessors for these objects and delegate them to `HandlebarsRenderer`.
* Change `assembler` attribute to `_assembler` to signal that this should not be accessed directly.

STRF-4420: Remove direct access to siteSettings and themeSettings

---

helpers/getFontLoaderConfig.js
helpers/getFontsCollection.js
helpers/resourceHints.js
lib/fonts.js
test/helpers/getFontLoaderConfig.js
test/helpers/resourceHints.js

* Extract font logic from getFontsCollection helper to make it reusable
* Add `resourceHints` helper that generates a set of <link> tags for
preconnect and dns-prefetch resource hints. This uses the font parsing
logic from getFontsCollection helper to determine which font providers
are used for the theme, and adds resource hints for expected hosts
for these font providers. Also add one for the cdn host.
* Add `getFontLoaderConfig` helper that generates a config suitable for
use in Web Font Loader.
* This will become 2.0.8 and will need to be ported over to 3.0

STRF-4605: Add resourceHints helper

---

.travis.yml
CHANGELOG.md
README.md
index.js
package.json
spec/index.js

To prepare for off-loading render tasks to a separate thread pool, update interfaces to be Promise-based rather than return synchronous results. This is a breaking change, but since we are still in release candidate stage, we can stay at 3.0.
Breaking changes:
* Use paper-handlebars 4.0.0, which uses Promises for `render` and `renderString`.
* Change `loadTheme`, `loadTemplates`, `loadTranslations`, `render`, `renderString`, and `renderTheme` to be based on Promises rather than callbacks.
* Update assembler interface to expect that it returns a promise.
* Drop support for Node 4.x
Other changes:
* Remove Async dependency
* Fill out missing changelog entries
* Update readme to demonstrate new interface
* Add support for Node 10.x
Depends on …

STRF-5485: Change to async interfaces

---

CHANGELOG.md
index.js
package.json
test/helpers/if.js
test/index.js

Backport cdnify fix in paper-handlebars 4.0.1 to the 2.x branch. Currently we are generating the cdn link for `img/icon-sprite.svg` with a double slash: `//img/icon-sprite.svg`. This fix avoids adding the extra slash.

Backport cdnify fix to 2.x

---

helpers/resourceHints.js
lib/fonts.js
test/helpers/getFontsCollection.js
test/helpers/resourceHints.js

Backport of paper-handlebars v4.0.3 to 2.x branch
* Update resourceHints to use https for font providers
* Update getFontsCollection to use https for font providers

Use http for font providers

---

CHANGELOG.md
package.json

* Bump paper-handlebars to 4.0.5
* Release v3.0.0-rc.11
@bigcommerce/storefront-team @bigcommerce/platform-engineering

Bump paper-handlebars to 4.0.5 & Release v3.0.0-rc.11

---

CHANGELOG.md
index.js
lib/logger.js
lib/translator/index.js
lib/translator/locale-parser.js
lib/translator/transformer.js
package.json
spec/lib/translator.js

The logger of this node module is only logging the error using console.log. This pr adds the option to pass logger. This is needed in case json log is needed (for ex. when the main app logging to logstash)

Added option to pass logger

---

CHANGELOG.md
package.json

Update paper-handlebars to latest.
Brings in the following from 4.0.7:
- Remove regex in cdnify.js to improve performance
- Remove regex in fonts.js for better performance
- Refactor functions away from arguments pattern for better performance
- Fix for helper to allow for one iteration
- Reduce usage of Lodash to improve performance
Brings in the following from 4.0.8:
- Update handlebars v4 to latest
- Update handlebars v3 to latest

STRF-6933: Update handlebars

---

CHANGELOG.md
package.json

Update paper to 2.0.16 to get imageSrcset and responsive images out to the world.

STRF-7011 release paper 2.0.16

---

CHANGELOG.md
helpers/getImage.js
helpers/getImageSrcset.js
helpers/setURLQueryParam.js
helpers/stripQuerystring.js
helpers/thirdParty.js
package.json
test/helpers/getImage.js
test/helpers/getImageSrcset.js
test/helpers/if.js
test/helpers/setURLQueryParam.js
test/helpers/stripQuerystring.js
test/helpers/thirdParty.js

- Add setURLQueryParam helper
- Make getImageSrcset not generate default srcsets larger than the original image when the dimensions are known
- Make getImage not generate an image larger than the dimensions of the original image if the dimensions are known
- Make getImage return SafeString again
- Allow stripQuerystring to accept SafeString
Should mirror this changeset:
https://github.com/bigcommerce/paper-handlebars/compare/v4.1.1...v4.2.0

Pull in paper-handlebars changes up to 4.2.0

---

CHANGELOG.md
package.json

This pr is part of a series of prs to upgrade cli to paper 3.x branch.
https://jira.bigcommerce.com/browse/STRF-7393

STRF-7393 bump paper-handlebars version to 4.2.2

---

CHANGELOG.md
index.js
package.json
spec/index.js

Previously, renderTheme function would not work properly when an ajax call resulted in having a templatePath with multiple templates.  This fix should allow it to work now.
https://jira.bigcommerce.com/browse/STRF-7393

STRF-7393 fix renderTheme function to work with Stencil CLI

---

CHANGELOG.md
package.json

Need to do a release on paper as git pull upstream master was not working properly and this caused an issue in stencil-cli where there was a diff in the code of the renderTheme function which is index.js of Paper.

bump paper to latest

---

CHANGELOG.md
lib/translator/locale-parser.js
package.json
spec/lib/translator.js

This should fix the issue of Safari only sending the most preferred language's code.  If the most preferred language's code does not exist then we go to the fallback for that language such as fr-CA to fr.  If neither of these locales exist then we fallback to English.  Tested in safari browser.
https://jira.bigcommerce.com/browse/STRF-7438

STRF-7438 fix stencil language translation in Safari

---

helpers/if.js
test/helpers/if.js

Use newer, more permissive code from paper-handlebars:
https://github.com/bigcommerce/paper-handlebars/blob/master/helpers/if.js
This should give better parity in the behavior of this helper.

Pull in newer "if" helper code from paper-handlebars to 2.x branch

---

CHANGELOG.md
package.json

- Backport more permissive behavior of if helper in subexpressions[#190](https://github.com/bigcommerce/paper/pull/190)

Release 2.0.21

---

CHANGELOG.md
helpers/encodeHtmlEntities.js
package.json
test/helpers/encodeHtmlEntities.js

Should match https://github.com/bigcommerce/paper-handlebars/pull/82 and https://github.com/bigcommerce/paper-handlebars/pull/83
ping @bigcommerce/storefront-team @lord2800

Update paper 2.x branch with encodeHtmlEntities helper and release

---

CHANGELOG.md
helpers/encodeHtmlEntities.js
package.json
test/helpers/encodeHtmlEntities.js

Should match https://github.com/bigcommerce/paper-handlebars/pull/88

Update encodeHtmlEntities helper to match paper-handlebars

---

.travis.yml
helpers/getContentImage.js
helpers/getContentImageSrcset.js
helpers/getImageManagerImage.js
helpers/getImageManagerImageSrcset.js
helpers/variables.js
index.js
lib/getObjectStorageImage.js
package-lock.json
package.json
test/helpers/assignVar-getVar.js
test/helpers/decrementVar.js
test/helpers/getContentImage.js
test/helpers/getContentImageSrcset.js
test/helpers/getImageManagerImage.js
test/helpers/getImageManagerImageSrcset.js
test/helpers/incrementVar.js

Pulling in these helpers:
https://github.com/bigcommerce/paper-handlebars/pull/95
https://github.com/bigcommerce/paper-handlebars/pull/96

Update paper 2.x branch to pull in latest helpers

---

.gitignore
CHANGELOG.md
package.json

* Update paper-handlebars to 4.4.1 (contains handlebars 3.x and 4.x upgrades)
* Release rc31

PEN-1911: Bump paper-handlebars and release rc31

---

.eslintrc
.travis.yml
package.json

- Updated .eslintrc to support newer JS syntax (set es2018 which is fully supported by node 10).
- Updated the ESLInt to the last version.
- Removed Node 8 from .travis.yml since we don't support it on paper v3.x (and the last version of ESlint doesn't support Node 8 either)
`npm run linter`
cc: @bigcommerce/storefront-team

feat: update ESLint to support newer JS syntax

---

package.json

4.5.x release of handlebar has a bug which needs to be fixed and it a rc candidate only.
@bigcommerce/storefront-team

Switch paper to stable paper handlebar version

---

CHANGELOG.md
package.json

chore: bump paper handlebars to 4.4.2 and release paper 3.0.0-rc.35

---

helpers/inject.js
test/helpers/inject.js

Updating the inject helper in paper 2.x 
Stapler needs to have parity with the change to the inject helper in paper-handlebars that will be used by storefront-renderer.
See: https://github.com/bigcommerce/paper-handlebars/pull/110
Ran Stapler in my VM with my branch of Paper referenced, ensured values in jsContext were escaped the same way as in the PR above.
@bigcommerce/storefront-team

BCTHEME-276 Escape values in inject helper

---

CHANGELOG.md
package.json

Release 3.0.0-rc.38 and bump paper handlebars to 4.4.6

Release 3.0.0-rc.38 and paper handlebars 4.4.6

---

lib/translator/index.js
package.json
spec/lib/translator.js

1. Introduce option disablePluralKeyChecks
2. Before version 2 messageformat was ignoring if the keys in the message are wrong, now it throws an error. disablePluralKeyChecks() function is used to disable that check
3. Some messageformat methods(plurals, select, etc.), that are used in precompiling templates are not in the global scope, so  added them to the global scope
cc @junedkazi @jmwiese @pachanady

STRF-9219 Fix Polyglot exceptions for precompileTranslations

---

lib/translator/index.js
spec/lib/translator.js

1) In case if translation key is not string, we try to set it to string.
2) Do not break render operation if some translation key is not possible to precompile because of wrongly formatted (or other reason)

STRF-9227 Address Polyglot exceptions

---

package.json

Note, but build should pass once `paper-handlebars` PR has been merged and released. Currently build is failing to install packages as I am using a remote url for `paper-handlebars` package.
Region name localization support. This PR is to add `content-region-translation` data attribute if translation is provided in the html handlebars from the theme. This will be used to surface the correct translation on the front end (page builder) for a particular region.
Steps to test 
(1) Pull down the `storefront-render` [PR](https://github.com/bigcommerce/storefront-renderer/pull/280) and run locally (or can run the container image) 
(2) Pull down `stencil-cli` [PR](https://github.com/bigcommerce/stencil-cli/pull/731) and create theme with `{{{region name="header_bottom" …

MERC-7830 region name localization support

---

CHANGELOG.md
package.json

Release version 3.0.0-rc.47.
Bump paper handlebars version to latest, includes changes to support region translations

Release version 3.0.0-rc.47

---

lib/translator/index.js
lib/translator/locale-parser.js
package.json
spec/lib/translator.js

1. Removed **disablePluralKeyChecks** option as it's not supported anymore
2. "Zero" key is invalid for lang "en". (https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html)
Before library was ignoring it, now it throws an error. In cornerstone we don't have it (https://github.com/bigcommerce/cornerstone/blob/master/lang/en.json), but other developers might have it.
3. There is change in **lang** helper logic. Before it was throwing a SyntaxError if there is some "syntax error", now it always a generic Error. So the idea is to throw an error always when the value is invalid and log a message. 
cc @bookernath, @bigcommerce/storefront-team

STRF-9222 Replace/upgrade deprecated messageformat library

---

.github/workflows/release.yml
CHANGELOG.md
package.json

- Bumps paper-handlebars to 4.4.9 [#252](https://github.com/bigcommerce/paper/pull/252)
- Release paper package through Github Actions [#251](https://github.com/bigcommerce/paper/pull/251)

Release 3.0.0-rc.49

---

index.js
lib/translator/index.js
lib/translator/locale-parser.js
package.json
spec/index.js
spec/lib/translator.js

- Reverted messageformat library to 0.2.2, that was before GraalVM work.
- Removed logic for translation precompilation and corresponding tests

STRF-9379 Revert messageformat to pre-GraalVM condition

---

CHANGELOG.md
package.json

- Reverted messageformat library to 0.2.2 [#253](https://github.com/bigcommerce/paper/pull/253)

Release 3.0.0-rc.50

---

index.js
lib/translator/index.js
spec/lib/translator.js

Revert some changes over the past year that are unused or related to other reversions.
* Revert addition of `preprocess` and `addTemplates` which are unused
* Revert refactor that exposed `setLanguage` function which is unused outside of `Translator` class
* Remove unused `Translator.compileFormatterFunction`
* Revert changes to translation compilation error handling leftover from failed MessageFormat upgrade

Revert some unused code

---

lib/translator/filter.js
lib/translator/index.js
spec/fixtures/lang.json
spec/lib/filter.js
spec/lib/translator.js

* Refactor filterByKey
* Add some documentation on the expected structure of the language object
* Optimize code for the expected data structure, making it a bit more readable
* Add fixture for lang file (comes from Cornerstone)
* Add tests for Filter class
* A couple of other small cleanup changes
I examined the output of the `langJson` helper (which uses `filterByKey`) and verified that the output is the same with this change.

Code cleanup

---

CHANGELOG.md
lib/translator/filter.js
lib/translator/index.js
lib/translator/locale-parser.js
lib/translator/transformer.js
spec/lib/filter.js
spec/lib/transformer.js
spec/lib/translator.js

Improve performance of Transformer
* Note that this PR updates the interface for the functions in `lib/translator/transformer.js` and `lib/translator/locale-parser.js`, but these methods should be considered private to the Translator class so should not constitute a breaking change. The interface for Translator remains the same.
* Use imperative style for Transformer cascade and flatten
* Transformer cascade and flatten now only process the data for the preferred locale, rather than all top level locales. This also changes the return value to a single language, rather than all languages.
* Change LocaleParser.getPreferredLocale to getPreferredLocales (plural) and have it return an ordered list of locales based on the Accept-Language header
* Change Transformer.transform to take a list of …

Performance improvements for translations

---

CHANGELOG.md
index.js
package.json

STRF-9658 log level support for hb logger

---

CHANGELOG.md
lib/translator/index.js
lib/translator/transformer.js
spec/lib/translator.js

To omit sentry, we are going to mark MessageFormat errors as warning

feat: STRF-9705 MessageFormat errors mark as warning

---

CHANGELOG.md
package.json

- bump paper-handlebars: STRF-9835 Reduce proto usage [278](https://github.com/bigcommerce/paper/pull/278)
- drop node 12 support  [277](https://github.com/bigcommerce/paper/pull/277)
cc @bigcommece/storefront-team

chore: release 4.0.0

---

CHANGELOG.md
package.json

- bump paper-handlebars: Fix replacement `get` and `option` helpers for backwards-compatibility [282](https://github.com/bigcommerce/paper/pull/282)

chore: release 4.0.2

---

CHANGELOG.md
package.json

- bump paper-handlebars: bugfix & setup to replace 3p helpers incrementally: `moment` and `option` ([#178](https://github.com/bigcommerce/paper-handlebars/pull/178)

chore: release 4.0.3

---

CHANGELOG.md
package.json

- bump paper-handlebars: setup to replace `get` & `getObject` helpers ([#183](https://github.com/bigcommerce/paper-handlebars/pull/183))

chore: release 4.0.5

---

CHANGELOG.md
package.json

- bump paper-handlebars: bugfix for edge case affecting `get`, `getObject`, and `option` ([#185](https://github.com/bigcommerce/paper-handlebars/pull/185))

chore: release 4.0.6

---

index.js
package.json
spec/index.js

`Paper` includes a getter of renderer's resource hints.
If any helper included in the theme/template/string was
configured to produce a resource hint, then,
AFTER A SUCCESSFUL rendering, this getter may be called.
For more details check https://github.com/bigcommerce/paper-handlebars/blob/master/helpers/lib/resourceHints.js

[STRF-9951] expose getter to access renderer's resource hints.

---

CHANGELOG.md
package.json

- `Paper` exposes a getter to extract the renderer's resource hints. ([#285](https://github.com/bigcommerce/paper/pull/285))

chore: release 4.1.0

---

CHANGELOG.md
package.json

- Add a a getter in Paper to access the renderer object. ([#287](https://github.com/bigcommerce/paper/pull/287))
@jairo-bc

Release 4.1.1

---

CHANGELOG.md
package.json

- Bumps paper-handlebars version ([#293](https://github.com/bigcommerce/paper/pull/293))
cc @bigcomerce/storefront-team

chore: bump paper handlebars

---

CHANGELOG.md
package.json

- Bumps paper-handlebars version ([#294](https://github.com/bigcommerce/paper/pull/294))

chore: release 4.1.5

---

CHANGELOG.md
package.json

- ref: Bump paper-handlebars version: STRF-10124 clean up hbs helpers ([#297](https://github.com/bigcommerce/paper/pull/297))

chore(release): 4.1.7

---

package.json

Need to bump handlebars to 5.7.8 after a small change to the `{{ money }}` helper
@bigcommerce/storefront-team

fix: STRF-10878 Bump handlebars to 5.7.8

---

package.json

Use CDN Original images for webdav - cache control. 
If a developer/merchant decide to use the handlebar to import images from WebDav into the theme `({{cdn "webdav:/img/image.jpg"}})`, there is no cache-control header when the image is presented to the storefront.
Similar to our Image Manager, we should be using the cdn original images (Similar to Jinsoo's PR here [MERC-7127](https://github.com/bigcommerce/bigcommerce/pull/47254)
Tested locally
[MERC-7127]: https://bigcommercecloud.atlassian.net/browse/MERC-7127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(merc): Bump paper handlebars - webdav cache control

---

.github/PULL_REQUEST_TEMPLATE.md
package.json

Bumping versions to fix semantic release PR creation.
Added github PR template.
in paper-handlerbars
----

fix: semantic release auto-PR creation

---

package.json

Reverts `paper-handlebars` Webdav CDN Url
fix(merc): MERC-9364 bump paper handlebars - revert CDN Webdav Url

fix(merc): MERC-9364 bump paper handlebars - revert CDN Webdav Url

---

package.json

bump paper hbs version
npm test
----

fix: bump paper hbs with chrono updates

---

package.json

bump paper handlebars with handlebars v4 update
- cdvm
- npm test
----

fix: bump paper handlebars to 5.9.5

---

package.json

bump paper-handlebars to 5.10.1
----

fix: bump hbs to 5.10.1

---

index.js
spec/index.js

Added public methods for:
- addTemplates
- addTranslations
- getPreProcessor
- npm test
- cdvm
----

feat: STRF-11908 Provide public endpoints for setting templates and translations

---

package.json

Bump paper handlebars
Tested with paper handlebars PRs
----

fix: bump paper handlebars to 5.10.3

---

package.json

Bump paper handlebars to remove quotes from nonce handlebars helper - https://github.com/bigcommerce/paper-handlebars/pull/309
1. Pull PR locally
2. Within directory use `npm link`
3. Inside storefront-renderer-2 run `npm link @bigcommerce/stencil-paper`
4. Run storefront-renderer-2 locally and turn on STRF-11672.Enable_nonce_csp_header
5. Add to script manager
```
<script>
{{nonce}}
</script>
```
7. See that nonce is shown without outer quotes, and is also displayed in attributes section of the script tag
[STRF-11672.Enable_nonce_csp_header](https://app.launchdarkly.com/default/development/features/STRF-11672.Enable_nonce_csp_header) on
[STRF-11672.Enable_nonce_csp_header](https://app.launchdarkly.com/default/development/features/STRF-11672.Enable_nonce_csp_header) off 
8. Ongoing work …

fix: bump paper handlebars to 5.10.4

---

package.json

Bump paper-handlebars version to latest.
Roll back this PR
n/a
----
cc @bigcommerce/team-storefront 
[STRF-12281]: https://bigcommercecloud.atlassian.net/browse/STRF-12281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(storefront): STRF-12281 Bump paper-handlebars version

---

package.json

bump paper-handlebars with https://github.com/bigcommerce/paper-handlebars/pull/331
----
cc @bigcommerce/team-storefront

fix: STRF-12234 bump paper-handlebars

---

package.json

More https://github.com/bigcommerce/paper-handlebars/pull/333
npm test
----

fix: bump paper handlebars version

---

lib/translator/index.js
package.json
spec/lib/translator.js

The previous version of messageformat (which is quite old) uses underscore which has a security vulnerability
https://github.com/bigcommerce/storefront-renderer-2/security/dependabot/4
This updates to the closest version which doesnt not have underscore
Tested locally
Before:
After:
----

fix(storefront): STRF-12688 Update messageformat dependency

---

package.json

https://github.com/bigcommerce/paper-handlebars/pull/345
npm test
----

fix: bump paper handlebars version to 6.0.3

---

package.json

more here: https://github.com/bigcommerce/paper-handlebars/pull/347
npm test 
----

fix: bump paper hbs to 6.0.4

---

package.json

release hbs bump to 6.2.2
npm test 
----

fix: release 6.2.2 hbs

---

package.json

release paper-handlebars to 6.2.3 
npm test
----

fix: bump paper hbs to 6.2.3

---

index.js
package.json

This PR adds a new version of `paper-handlebars` for adding webdav cache-control.  HandlebarsRenderer is chosen based on experiment `SD-9364.Use_cdn_original_content_for_webdav_images`.
Based on https://github.com/bigcommerce/paper-handlebars/pull/298
tested locally via postman
results can be seen [here](https://github.com/bigcommerce/storefront-renderer-2/pull/118)
----

fix: add new paper handlebars version for webdav cache control

---

package.json

bump paper handlebars
npm test
----

fix: bump paper hbs to 6.3.1

---

package.json

bump paper-handlebars 6.3.2
npm test
----

fix: bump paper hbs to 6.3.2
