- helpers/getImage.js
- test/helpers/getImage.js
@hegrec @mcampa @mickr @bc-ejoe 
https://github.com/bigcommerce/stencil/pull/797
> MERC-616 support customized image dimension preset

- helpers/getImage.js
- test/helpers/getImage.js
> MERC-907 getImage is broken for carousel images

- package.json
> MERC-907 version bump

- .travis.yml
- index.js
- package.json
- test/index.js
> MERC-1057 Add session id to the cdn url

- index.js
- test/index.js
> MERC-1057 Add "e" to the cdl url path to fix stapler route conflict

- package.json
I forgot to bump version 😞 
@lord2800
> bump version to 1.1.2

- .eslintrc
- helpers/block.js
- helpers/compare.js
- helpers/deprecated.js
- helpers/for.js
- helpers/getFontsCollection.js
- helpers/helperMissing.js
- helpers/if.js
- helpers/inject.js
- helpers/join.js
- helpers/lang.js
- helpers/or.js
- helpers/replace.js
- helpers/stylesheet.js
- index.js
- test/helpers/block.js
- test/helpers/cdn.js
- test/helpers/replace.js
This type of errors were thrown and preventing the page from getting rendered after editing the usage of the block helper in the file editor. For example
```
if you change
{{#partial foo}}Hello{{/partial}}
to
{{#partial}}Hello{{/partial}}
```
It thrown an error and it does not render the page
I fixed all helpers using "options" as the last argument
@lord2800 @mattolson
> MERC-1372 fix an error that prevents the page for rendering

- .gitignore
- helpers/thirdParty.js
- package.json
- test/helpers/thirdParty.js
* adds and exposes the helpers we've selected from the [handlebars-helpers library](https://github.com/helpers/handlebars-helpers)
* https://jira.bigcommerce.com/browse/STENCIL-3323
@bigcommerce/stencil-team @bookernath
> STENCIL-3323 - Implement approved Handlebars helpers from pack

- CHANGELOG.md
- package.json
> Version bump 2.0.0

- helpers/getFontsCollection.js
@mcampa - this is needed to prepare to upgrade some of the deps in cli
> STENCIL-3672 - _.uniq instead of _.unique

- helpers/replace.js
- test/helpers/replace.js
Fix issue https://github.com/bigcommerce/paper/issues/124
@bigcommerce/stencil-team @flyingL123
> STENCIL-3850 'replace' helper inconsistent search vs replace

- helpers/replace.js
- test/helpers/replace.js
@mattolson @bigcommerce/stencil-team
> replace helper bug fix

- README.md
> Add link to helper reference documentation

- package.json
* Update paper-handlebars to latest
* Bump version to rc4
> STRF-4917: Update paper-handlebars

- CHANGELOG.md
- package.json
* Bump paper-handlebars to 4.0.3
* Release 3.0.0-rc.9
> Bump paper-handlebars to 4.0.3 and release rc9

- CHANGELOG.md
- helpers/for.js
- test/helpers/for.js
This pull request is to change behavior of for helper to allow for single iteration.
Fixes #90
> STRF-6836 For helper should iterate once

- CHANGELOG.md
- package.json
Update handlebars to latest 3.0.7
> STRF-6933: Update handlebars

- CHANGELOG.md
- package.json
* Bump paper-handlebars to 3.0.9
* Release rc.15
> STRF-6935: Bump paper-handlebars

- CHANGELOG.md
- package.json
* Bump paper-handlebars to 4.1.0
* Release rc.16
> STRF-7011 upgrade paper-handlebars to 4.1.0

- helpers/getImageSrcset.js
- lib/common.js
- package.json
- test/helpers/getImageSrcset.js
Should mirror https://github.com/bigcommerce/paper-handlebars/pull/42
> Add getImageSrcset helper to paper 2.x branch

- CHANGELOG.md
- helpers/getImage.js
- test/helpers/getImage.js
Should mirror https://github.com/bigcommerce/paper-handlebars/pull/61
Also added changelog
> Pull in other image updates

- CHANGELOG.md
- helpers/getImage.js
- package.json
- test/helpers/getImage.js
Should mirror https://github.com/bigcommerce/paper-handlebars/pull/65
> Undo safestring changes to getImage and release 2.0.17

- helpers/json.js
- helpers/setURLQueryParam.js
- helpers/stripQuerystring.js
- lib/common.js
- test/helpers/json.js
Bring in these changes:
https://github.com/bigcommerce/paper-handlebars/commit/0ffd5a1b96e48e2945275be56d3863187a40957f
https://github.com/bigcommerce/paper-handlebars/commit/011d9a5a7501183e4e21e3ae7b5749581767a3b4
ping @bigcommerce/storefront-team
> Bring 2.x branch up to date with json SafeString changes

- CHANGELOG.md
- package.json
> bump paper version

- CHANGELOG.md
- lib/translator/locale-parser.js
- package.json
- test/lib/translator.spec.js
Backport of the fix that was made to fix safari translation issue.
Related to: https://github.com/bigcommerce/paper/pull/186
> STRF-7438 fix stencil language translation in Safari

- helpers/replace.js
- package.json
- test/helpers/replace.js
Should match https://github.com/bigcommerce/paper-handlebars/pull/92
> Allow replace helper to accept safestrings, release 2.0.24

- CHANGELOG.md
- package.json
ping @bigcommerce/storefront-team
> Bump paper-handlebars to 4.4.0, release rc30

- .gitignore
- CHANGELOG.md
- index.js
- lib/translator/filter.js
- lib/translator/index.js
- lib/translator/locale-parser.js
- lib/translator/transformer.js
- package.json
Refactor the Translator and remove unneeded dependency
> Refactor Translator and remove unneeded dependency

- package.json
> Release paper 2.0.26

- CHANGELOG.md
- package.json
@mattolson @bigcommerce/storefront-team
> update paper handlebars to a stable version

- CHANGELOG.md
- package.json
Bump paper-handlebars to latest
> STRF-8864: Bump paper-handlebars to 4.4.3

- CHANGELOG.md
- helpers/occurrences.js
- helpers/thirdParty.js
- package.json
- test/helpers/occurrences.js
* Lift occurrences helper from handlebars-helpers
* Add missing release notes
* Cut version 2.0.27
Added unit tests
----
> STRF-8864: Lift occurrences helper & release 2.0.27

- CHANGELOG.md
- package.json
> Bump paper-handlebars and release paper

- CHANGELOG.md
- package.json
this bump involves the following PR
https://github.com/bigcommerce/paper/pull/215
@bigcommerce/storefront-team
> Release 2.0.28

- index.js
Add public interfaces for template preprocessing.
> STRF-9043 Break out precompilation logic into its own endpoint

- CHANGELOG.md
- package.json
> Release 3.0.0-rc.39 and paper handlebars 4.4.7

- CHANGELOG.md
- package.json
> Release 3.0.0-rc.41

- package.json
Bumping to latest messageformat library
@junedkazi @jairo-bc @pachanady
> Bump messageformat library to 2.3.0

- CHANGELOG.md
- package.json
> New release 3.0.0-rc.44

- .github/workflows/release.yml
Github hook on release for the library for `npm publish`
> STRF-9317 Release stencil paper through github release

- lib/translator/index.js
- lib/translator/locale-parser.js
- lib/translator/transformer.js
- spec/lib/translator.js
Translation tree will be fallbacking to first available language translation in the chain, that comes from Accept Language Header.
> STRF-9553 Fallback languages in the chain

- CHANGELOG.md
- package.json
- STRF-9553 Fallback languages in the chain [#258](https://github.com/bigcommerce/paper/pull/258)
> Release 3.0.0-rc.53

- lib/translator/index.js
- package.json
- spec/lib/translator.js
* Fix bug in Translator constructor load test
* Minor refactor in Translator
* Increase test coverage requirement
> STRF-9434: Bug fix to load test

- CHANGELOG.md
- package.json
* Revert some unused code that should have been removed as part of previous reversions [#260](https://github.com/bigcommerce/paper/pull/260)
* Cleanup filterByKey [#261](https://github.com/bigcommerce/paper/pull/261)
* Improve performance of Translator constructor through internal refactor of Transformer [#262](https://github.com/bigcommerce/paper/pull/262)
> Release rc.54

- index.js
Add an accessor method for the renderer instance with in paper.
@jairo-bc
> Add accessor for renderer

- package.json
- spec/index.js
> Updates paper handlebars

- CHANGELOG.md
- package.json
> chore: release 4.1.2

- package.json
CC @bigcommerce/storefront-team
> [STRF-10096] Updates paper-handlebars

- CHANGELOG.md
- package.json
CC @bigcommerce/storefront-team
> chore: release 4.1.3

- CHANGELOG.md
- package.json
> chore release 4.1.6

- .github/workflows/build.yml
- .github/workflows/release.yml
- .husky/commit-msg
- .releaserc
- commitlint.config.js
- package.json
We are going to follow semantic commit name conventions to be able to auto bump package versions.
So each PR is released when merged.
Auto-bump version
PR title and commit message validation to follow convention.
Auto-github release created
> feat: STRF-10157 Introduce Semantic Release

- package.json
fix lodash removal issues (null params)
> fix: bump paper handlebars

- package.json
> feat: bump paper hbs

- package.json
CC: @bigcommerce/storefront-team
> feat: bump paper-handlebars

- package.json
> fix: bump hbs to 5.7.3

- package.json
> fix: bump hbs to 5.7.4

- package.json
CC @bigcommerce/storefront-team
> fix: bump hbs to 5.7.5

- package.json
CC @bigcommerce/storefront-team
> fix: bump hbs to 5.7.6

- package.json
> fix: bump hbs to 5.7.7

- index.js
- package.json
- spec/index.js
Pass down request params to paper-handlebars.
Bump  paper-handlebars version 
npm test
----
> feat: STRF-11819 Pass down to hbs request params

- .github/workflows/build.yml
> fix: STRF-11934 Move PR Title to env 

- .github/dependabot.yml
> feat: STRF-12284 Add dependabot to paper

- package.json
bump paper hanblebars
More here: https://github.com/bigcommerce/paper-handlebars/pull/322
----
> fix: bump paper hbs

- package.json
https://github.com/bigcommerce/paper-handlebars/compare/v6.0.4...v6.2.1
npm test 
----
> feat: arguments usage improvements and new typeof helper
